listen = "[::1]:8080"

assets-dir    = "./assets"
templates-dir = "./templates"
db-dir        = "./"

motherlode = true

[postgres]
user     = "msgp"
password = "msgp"
database = "msgp"
address  = "localhost"
port     = "5432"